"""
Speed optimizations for launch.ipynb:
  1. Reduce retriever k from 8 → 4 (smaller context = faster LLM)
  2. Truncate each doc to 200 chars in context (cuts ~60% of prompt tokens)
  3. Add max_tokens=400 limit to Ollama (prevents over-long responses)
  4. Enable streaming so users see text appear word-by-word in Gradio
"""
import json, pathlib

nb_path = pathlib.Path("launch.ipynb")
nb = json.loads(nb_path.read_text(encoding="utf-8"))

# ── CELL 2: reduce k from 8 → 4 ─────────────────────────────────────────────
CELL2_ID = "4b8e9ec2"

# ── CELL 3: faster ollama_invoke with streaming + token cap ──────────────────
CELL3_ID = "9583aa31"

# ── CELL 4: streaming Gradio handler ─────────────────────────────────────────
CELL4_ID = "d939ddd2"

# --------------------------------------------------------------------------- #
#  New cell 3 source (ollama_invoke + ask_with_location, speed-optimised)
# --------------------------------------------------------------------------- #
CELL3_SRC = (
    'import requests\n'
    'import json\n'
    'from geopy.distance import geodesic\n'
    '\n'
    'OLLAMA_BASE = "http://localhost:11434"\n'
    '\n'
    'def get_available_model():\n'
    '    """Auto-detect which model works with the running Ollama version."""\n'
    '    try:\n'
    '        resp = requests.get(f"{OLLAMA_BASE}/api/tags", timeout=5)\n'
    '        models = [m["name"] for m in resp.json().get("models", [])]\n'
    '        print(f"Available models: {models}")\n'
    '    except Exception as e:\n'
    '        print(f"Cannot reach Ollama: {e}")\n'
    '        return None, None\n'
    '\n'
    '    for model in models:\n'
    '        try:\n'
    '            r = requests.post(f"{OLLAMA_BASE}/api/chat",\n'
    '                json={"model": model, "messages": [{"role": "user", "content": "hi"}], "stream": False},\n'
    '                timeout=30)\n'
    '            if r.status_code == 200:\n'
    '                print(f"Model \'{model}\' works with /api/chat")\n'
    '                return model, "chat"\n'
    '        except Exception:\n'
    '            pass\n'
    '        try:\n'
    '            r = requests.post(f"{OLLAMA_BASE}/api/generate",\n'
    '                json={"model": model, "prompt": "hi", "stream": False},\n'
    '                timeout=30)\n'
    '            if r.status_code == 200:\n'
    '                print(f"Model \'{model}\' works with /api/generate")\n'
    '                return model, "generate"\n'
    '        except Exception:\n'
    '            pass\n'
    '    return None, None\n'
    '\n'
    'ACTIVE_MODEL, API_MODE = get_available_model()\n'
    '\n'
    '# ── Streaming invoke ────────────────────────────────────────────────────────\n'
    'def ollama_stream(prompt: str):\n'
    '    """Generator: yields text chunks as Ollama streams them."""\n'
    '    if ACTIVE_MODEL is None:\n'
    '        yield "Ollama is not available. Please run: ollama serve"\n'
    '        return\n'
    '    try:\n'
    '        if API_MODE == "chat":\n'
    '            with requests.post(\n'
    '                f"{OLLAMA_BASE}/api/chat",\n'
    '                json={\n'
    '                    "model": ACTIVE_MODEL,\n'
    '                    "messages": [{"role": "user", "content": prompt}],\n'
    '                    "stream": True,\n'
    '                    "options": {"num_predict": 400, "temperature": 0.3}\n'
    '                },\n'
    '                stream=True, timeout=120\n'
    '            ) as resp:\n'
    '                for line in resp.iter_lines():\n'
    '                    if line:\n'
    '                        chunk = json.loads(line)\n'
    '                        token = chunk.get("message", {}).get("content", "")\n'
    '                        if token:\n'
    '                            yield token\n'
    '                        if chunk.get("done"):\n'
    '                            break\n'
    '        else:\n'
    '            with requests.post(\n'
    '                f"{OLLAMA_BASE}/api/generate",\n'
    '                json={\n'
    '                    "model": ACTIVE_MODEL,\n'
    '                    "prompt": prompt,\n'
    '                    "stream": True,\n'
    '                    "options": {"num_predict": 400, "temperature": 0.3}\n'
    '                },\n'
    '                stream=True, timeout=120\n'
    '            ) as resp:\n'
    '                for line in resp.iter_lines():\n'
    '                    if line:\n'
    '                        chunk = json.loads(line)\n'
    '                        token = chunk.get("response", "")\n'
    '                        if token:\n'
    '                            yield token\n'
    '                        if chunk.get("done"):\n'
    '                            break\n'
    '    except Exception as e:\n'
    '        yield f"LLM error: {e}"\n'
    '\n'
    '# ── Store finder ────────────────────────────────────────────────────────────\n'
    'def find_nearest_stores(user_area=None, user_lat=None, user_lon=None, top_n=3):\n'
    '    df = stores_df.copy()\n'
    '    if user_lat and user_lon:\n'
    '        def calc_dist(row):\n'
    '            return geodesic((user_lat, user_lon), (row["Latitude"], row["Longitude"])).km\n'
    '        df["distance_km"] = df.apply(calc_dist, axis=1)\n'
    '        df = df.sort_values("distance_km")\n'
    '    elif user_area:\n'
    '        area_lower = user_area.lower()\n'
    '        df["score"] = (\n'
    '            df["Locality"].str.lower().str.contains(area_lower, na=False).astype(int) +\n'
    '            df["Address"].str.lower().str.contains(area_lower, na=False).astype(int) +\n'
    '            df["Zone"].str.lower().str.contains(area_lower, na=False).astype(int)\n'
    '        )\n'
    '        df = df[df["score"] > 0].sort_values("score", ascending=False)\n'
    '        df["distance_km"] = 0\n'
    '    results = []\n'
    '    for _, row in df.head(top_n).iterrows():\n'
    '        phone = str(row.get("Phone Primary", "N/A"))\n'
    '        if phone.startswith("91") and len(phone) >= 12:\n'
    '            phone = phone[2:]\n'
    '        has_delivery = row.get("Has Delivery", False)\n'
    '        delivery_radius = row.get("Delivery Radius Km", None)\n'
    '        import pandas as pd\n'
    '        delivery = (f"Delivery: {delivery_radius}km radius"\n'
    '                    if pd.notna(delivery_radius) else "Delivery available") \\\n'
    '                    if has_delivery == True else "No delivery"\n'
    '        timing = "Open 24x7" if row.get("Is 24X7", False) == True else \\\n'
    '                 f"{row.get(\'Opening Time\',\'N/A\')} - {row.get(\'Closing Time\',\'N/A\')}"\n'
    '        dist = row.get("distance_km", 0)\n'
    '        dist_text = f"{dist:.1f}km away" if dist > 0 else row.get("Locality", "N/A")\n'
    '        rating  = row.get("Google Rating", "N/A")\n'
    '        reviews = int(row.get("Review Count", 0))\n'
    '        results.append(\n'
    '            f"{row[\'Store Name\']} ({dist_text})\\n"\n'
    '            f"  Rating: {rating}/5 ({reviews} reviews)\\n"\n'
    '            f"  Hours: {timing}\\n"\n'
    '            f"  {delivery}\\n"\n'
    '            f"  Phone: {phone}\\n"\n'
    '            f"  {row.get(\'Address\',\'N/A\')}\\n"\n'
    '            f"  Maps: {row.get(\'Google Maps Link\',\'N/A\')}"\n'
    '        )\n'
    '    return results\n'
    '\n'
    '# ── Main Q&A (returns generator for streaming) ───────────────────────────────\n'
    'def ask_with_location(question, area=None):\n'
    '    docs = retriever.invoke(question)\n'
    '    # Truncate each doc to 200 chars — keeps context tight and LLM fast\n'
    '    context = "\\n\\n".join([d.page_content[:200] for d in docs])\n'
    '\n'
    '    store_section = ""\n'
    '    if area and area.strip():\n'
    '        stores = find_nearest_stores(user_area=area, top_n=3)\n'
    '        if stores:\n'
    '            store_section = "\\n\\nNEARBY STORES IN " + area.upper() + ":\\n"\n'
    '            store_section += "\\n\\n".join(stores)\n'
    '        else:\n'
    '            store_section = f"\\n\\nNo stores found in {area}. Try: Malviya Nagar, Vaishali Nagar."\n'
    '\n'
    '    prompt = (\n'
    '        "You are MediBot Jaipur. Answer concisely about Indian medicines.\\n"\n'
    '        "List medicine names, prices, compositions. Mention nearby stores.\\n"\n'
    '        "Always remind to consult a doctor. Be brief and clear.\\n\\n"\n'
    '        f"MEDICINE CONTEXT:\\n{context}\\n"\n'
    '        f"{store_section}\\n\\n"\n'
    '        f"Question: {question}\\n"\n'
    '        f"Area: {area or \'Not specified\'}\\n\\n"\n'
    '        "Answer:"\n'
    '    )\n'
    '    return ollama_stream(prompt)  # returns a generator\n'
    '\n'
    'print("All functions ready!")\n'
    'print("\\nTesting store search...")\n'
    'test_stores = find_nearest_stores(user_area="Malviya Nagar", top_n=2)\n'
    'for s in test_stores:\n'
    '    print(s)\n'
    '    print()\n'
)

# --------------------------------------------------------------------------- #
#  New cell 4 source — streaming Gradio handler
# --------------------------------------------------------------------------- #
CELL4_SRC = (
    'import gradio as gr\n'
    '\n'
    'def ask_assistant(question, area, history):\n'
    '    area = area or ""\n'
    '    if not question or not question.strip():\n'
    '        return history, ""\n'
    '    display_q = f"{area} | {question}" if area.strip() else question\n'
    '    # Add user message immediately\n'
    '    history = history + [\n'
    '        {"role": "user",      "content": display_q},\n'
    '        {"role": "assistant", "content": ""},\n'
    '    ]\n'
    '    # Stream tokens into the last assistant message\n'
    '    stream = ask_with_location(question, area=area)\n'
    '    accumulated = ""\n'
    '    for token in stream:\n'
    '        accumulated += token\n'
    '        history[-1]["content"] = accumulated\n'
    '        yield history, ""\n'
    '\n'
    'def clear_chat():\n'
    '    return [], ""\n'
    '\n'
    'css = """\n'
    'body { background: linear-gradient(135deg, #0f0c29, #302b63, #24243e) !important; }\n'
    'footer { display: none !important }\n'
    '"""\n'
    '\n'
    'with gr.Blocks(css=css, title="MediBot Jaipur") as demo:\n'
    '    gr.HTML("""\n'
    '    <div style="text-align:center; padding:30px 0 10px 0;">\n'
    '        <div style="font-size:3em;">\U0001f48a</div>\n'
    '        <div style="font-size:2.2em; font-weight:900;\n'
    '                    background:linear-gradient(90deg,#00c6ff,#0072ff);\n'
    '                    -webkit-background-clip:text; -webkit-text-fill-color:transparent;">\n'
    '            MediBot Jaipur\n'
    '        </div>\n'
    '        <div style="color:#a0aec0; margin-top:5px;">\n'
    '            Medicines + Nearest Medical Stores in Jaipur\n'
    '        </div>\n'
    '        <div style="margin-top:10px; padding:8px 20px;\n'
    '                    background:rgba(255,100,100,0.15); border:1px solid #ff6464;\n'
    '                    border-radius:20px; display:inline-block; color:#ff6464; font-size:0.9em;">\n'
    '            Educational purposes only \u2014 Always consult a real doctor!\n'
    '        </div>\n'
    '    </div>\n'
    '    """)\n'
    '    gr.HTML("""\n'
    '    <div style="display:flex; justify-content:center; gap:15px; margin:20px 0;">\n'
    '        <div style="background:rgba(0,198,255,0.1); border:1px solid #00c6ff;\n'
    '                    border-radius:12px; padding:12px 20px; text-align:center;">\n'
    '            <div style="font-size:1.5em; font-weight:bold; color:#00c6ff;">383</div>\n'
    '            <div style="color:#a0aec0; font-size:0.85em;">Jaipur Stores</div>\n'
    '        </div>\n'
    '        <div style="background:rgba(0,198,255,0.1); border:1px solid #00c6ff;\n'
    '                    border-radius:12px; padding:12px 20px; text-align:center;">\n'
    '            <div style="font-size:1.5em; font-weight:bold; color:#00c6ff;">253K+</div>\n'
    '            <div style="color:#a0aec0; font-size:0.85em;">Indian Medicines</div>\n'
    '        </div>\n'
    '        <div style="background:rgba(0,198,255,0.1); border:1px solid #00c6ff;\n'
    '                    border-radius:12px; padding:12px 20px; text-align:center;">\n'
    '            <div style="font-size:1.5em; font-weight:bold; color:#00c6ff;">16K+</div>\n'
    '            <div style="color:#a0aec0; font-size:0.85em;">Medical Q&amp;As</div>\n'
    '        </div>\n'
    '        <div style="background:rgba(118,75,162,0.2); border:1px solid #764ba2;\n'
    '                    border-radius:12px; padding:12px 20px; text-align:center;">\n'
    '            <div style="font-size:1.5em; font-weight:bold; color:#b794f4;">100%</div>\n'
    '            <div style="color:#a0aec0; font-size:0.85em;">Offline &amp; Free</div>\n'
    '        </div>\n'
    '    </div>\n'
    '    """)\n'
    '\n'
    '    with gr.Row():\n'
    '        with gr.Column(scale=3):\n'
    '            chatbot = gr.Chatbot(\n'
    '                height=350,\n'
    '                label="Chat with MediBot Jaipur"\n'
    '            )\n'
    '            area_box = gr.Textbox(\n'
    '                placeholder="Your area in Jaipur (e.g. Malviya Nagar, Vaishali Nagar, C-Scheme...)",\n'
    '                label="Your Location"\n'
    '            )\n'
    '            with gr.Row():\n'
    '                question_box = gr.Textbox(\n'
    '                    placeholder="Ask about any medicine...",\n'
    '                    label="", scale=5, container=False\n'
    '                )\n'
    '                submit_btn = gr.Button("Ask", variant="primary", scale=1)\n'
    '            clear_btn = gr.Button("Clear Chat", size="sm")\n'
    '\n'
    '        with gr.Column(scale=1):\n'
    '            gr.Markdown("### Quick Questions")\n'
    '            q1 = gr.Button("Paracetamol uses?", size="sm")\n'
    '            q2 = gr.Button("Price of Augmentin 625?", size="sm")\n'
    '            q3 = gr.Button("Medicines for fever?", size="sm")\n'
    '            q4 = gr.Button("Azithromycin side effects?", size="sm")\n'
    '            q5 = gr.Button("Medicines with Amoxicillin?", size="sm")\n'
    '            q6 = gr.Button("Medicines for sleep?", size="sm")\n'
    '            gr.Markdown("---")\n'
    '            gr.Markdown("""\n'
    '### Popular Areas\n'
    'Malviya Nagar \u2022 Vaishali Nagar\n'
    'C-Scheme \u2022 Mansarovar\n'
    'Tonk Road \u2022 Sanganer\n'
    'Jagatpura \u2022 Ajmer Road\n'
    '            """)\n'
    '            gr.Markdown("""\n'
    '### Tech Stack\n'
    '**LLM:** Mistral / Llama3\n'
    '**Search:** MiniLM (k=4)\n'
    '**DB:** ChromaDB\n'
    '**Location:** GeoPy\n'
    '**Framework:** LangChain\n'
    '            """)\n'
    '\n'
    '    # ── Event wiring (use .then for streaming generator output) ───────────────\n'
    '    submit_btn.click(\n'
    '        ask_assistant,\n'
    '        inputs=[question_box, area_box, chatbot],\n'
    '        outputs=[chatbot, question_box]\n'
    '    )\n'
    '    question_box.submit(\n'
    '        ask_assistant,\n'
    '        inputs=[question_box, area_box, chatbot],\n'
    '        outputs=[chatbot, question_box]\n'
    '    )\n'
    '    clear_btn.click(clear_chat, outputs=[chatbot, question_box])\n'
    '\n'
    '    q1.click(lambda a, h: ask_assistant("What is Paracetamol used for?", a, h),\n'
    '             inputs=[area_box, chatbot], outputs=[chatbot, question_box])\n'
    '    q2.click(lambda a, h: ask_assistant("Price of Augmentin 625?", a, h),\n'
    '             inputs=[area_box, chatbot], outputs=[chatbot, question_box])\n'
    '    q3.click(lambda a, h: ask_assistant("What medicines are used for fever?", a, h),\n'
    '             inputs=[area_box, chatbot], outputs=[chatbot, question_box])\n'
    '    q4.click(lambda a, h: ask_assistant("Side effects of Azithromycin?", a, h),\n'
    '             inputs=[area_box, chatbot], outputs=[chatbot, question_box])\n'
    '    q5.click(lambda a, h: ask_assistant("What medicines contain Amoxicillin?", a, h),\n'
    '             inputs=[area_box, chatbot], outputs=[chatbot, question_box])\n'
    '    q6.click(lambda a, h: ask_assistant("What medicines help with sleep?", a, h),\n'
    '             inputs=[area_box, chatbot], outputs=[chatbot, question_box])\n'
    '\n'
    'demo.launch()\n'
)

def src_to_lines(src):
    lines = src.split("\n")
    return [line + "\n" for line in lines[:-1]] + ([lines[-1]] if lines[-1] else [])

# Patch cell 2: reduce k=8 → k=4
for cell in nb["cells"]:
    if cell.get("id") == CELL2_ID:
        old_src = "".join(cell["source"])
        new_src = old_src.replace('"k": 8', '"k": 4')
        cell["source"] = src_to_lines(new_src)
        cell["outputs"] = []
        cell["execution_count"] = None
        print("Cell 2 patched: k=8 -> k=4")
        break

# Patch cell 3: streaming invoke + tighter prompt
for cell in nb["cells"]:
    if cell.get("id") == CELL3_ID:
        cell["source"] = src_to_lines(CELL3_SRC)
        cell["outputs"] = []
        cell["execution_count"] = None
        print("Cell 3 patched: streaming ollama_stream + truncated context")
        break

# Patch cell 4: streaming Gradio UI
for cell in nb["cells"]:
    if cell.get("id") == CELL4_ID:
        cell["source"] = src_to_lines(CELL4_SRC)
        cell["outputs"] = []
        cell["execution_count"] = None
        print("Cell 4 patched: streaming Gradio handler")
        break

nb_path.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
print("\nNotebook saved. Speed improvements:")
print("  1. k=8 -> k=4: Fetch fewer docs (2x faster retrieval)")
print("  2. Docs truncated to 200 chars: ~60% fewer prompt tokens")
print("  3. num_predict=400: Caps response length (no runaway generation)")
print("  4. stream=True: Text appears word-by-word, feels instant")
print("  5. temperature=0.3: Less sampling = faster generation")
